version: "3.4"
services:

  db:
    image: postgres:12-alpine
    restart: always
    expose:
      - 5432
    environment:
      - "POSTGRES_PASSWORD=clojure"
      - "POSTGRES_USER=clojure"
      - "POSTGRES_DB=clojure"

  clj:
    build:
      context: ./clojure-webshop-api
      dockerfile: Dockerfile
    environment:
      - "DB_HOST=db"
      - "WEB_HOST=0.0.0.0"
    ports:
      - "3000:3000"
    command: java -jar server.jar
    depends_on:
      - db

  ui:
    build:
      context: ./clojure-webshop-ui
      dockerfile: Dockerfile
    restart: "always"
    ports:
      - "3449:3449"
      - "7888:7888"
    environment:
      - "DB_HOST=db"
      - "WEB_HOST=0.0.0.0"
    volumes:
      - clojure-webshop-ui:/clj
    depends_on:
      - db

volumes:
  clojure-webshop-ui:
